### ISSUE TITLE
Include a popup list of Services part of the new claim screen

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/primaza-poc#154]
## TODO

Add part of the `new claim` screen the popup list of the services registered

![Image](https://user-images.githubusercontent.com/463790/203791629-c6ab0515-0a30-4cc1-84f1-1128ebca0d05.png)

**Comment by Sgitario** [comment]
This change has been already done, however, I think it invalidates what the claiming service job is meant to. 
This job is intended to search the services that have been requested in a claim (something like "<service name>-<service version>"), but if we select the service from a popup, this is no longer necessary because we can always set a service id when creating or updating a claim.

**Comment by aureamunoz** [comment]
This is already done, can we close it @cmoulliard @Sgitario ?

**Comment by cmoulliard** [comment]
We can close it
