### ISSUE TITLE
Document what such methods invoked part of the creation of a cluster entity do

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/primaza-poc#172]
## TODO

Document what the following methods invoked part of the creation of a cluster entity do

https://github.com/halkyonio/primaza-poc/blob/3ec4715c5ca0a62a15cbfe6125fe5f2b982233c1/servicebox-app/src/main/java/io/halkyon/resource/page/ClusterResource.java#L78-L81

```
            serviceDiscoveryJob.checkCluster(cluster);
...
            applicationDiscoveryJob.syncApplicationsInCluster(cluster);
```

Additional question: Do we have to call them part of the logic to create a Cluster ?

**Comment by Sgitario** [comment]
All jobs are documented in the classes and also I think the class names are intuitive enough. 
Moreover, I think this matches what is described in the diagram workflows. 
Finally, this resource has changed since this issue was created. 
So, @cmoulliard do you think this issue is still relevant or we can close it?
