### ISSUE TITLE
Error: INSTALLATION FAILED: parse error at (fruits-app/templates/servicebinding.yaml:1): bad character U+002D '-'

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/primaza-poc#290]
## Issue

New demo-fruits.sh script raises an error when the helm chart is deployed
```
./scripts/demo-fruits.sh
$ k create ns app --dry-run=client -o yaml | k apply -f -
namespace/app configured
$ k config set-context --current --namespace=app
Context "kind-kind" modified.
$ helm repo add halkyonio http://halkyonio.github.io/helm-charts --force-update
"halkyonio" has been added to your repositories
$ helm install fruits-app halkyonio/fruits-app     -n app     --set app.image=quay.io/halkyonio/atomic-fruits:latest     --set app.host=atomic-fruits.127.0.0.1.nip.io
Error: INSTALLATION FAILED: parse error at (fruits-app/templates/servicebinding.yaml:1): bad character U+002D '-'
```

This problem is described here: https://github.com/helm/helm-www/issues/1272 and is related to the fact that th value name includes a dash "service-binding"

**Comment by Sgitario** [comment]
It seems the Helm does not allow having this kind of properties `service-binding.enabled`. I will prevent this kind of issues in Quarkus Helm (I've reported it in https://github.com/quarkiverse/quarkus-helm/issues/208).

And it's fixed by https://github.com/halkyonio/atomic-fruits-service/commit/fd8c0d2e55db183bc1d27f09c67919aeec47834d.

The Helm chart should be updated soon. Will keep this issue updated.

**Comment by Sgitario** [comment]
The charts have been already updated and this issue should be gone now. Closing.
