### ISSUE TITLE
Complete the logic for matching claims to services, and generating the secrets from the credentials

### ISSUE THREAD

**Issue by Sgitario** [halkyonio/primaza-poc#87]
Follow-up task of https://github.com/halkyonio/primaza-poc/pull/84
If a credential exists for a service available and matching the claim request, then update the claim to pass the credential.

Tasks:
- [x] Get deployments from the registered clusters: https://github.com/halkyonio/primaza-poc/pull/119
- [x] Implement Bind functionality: Select deployment, select claim and generate secrets plus rollout once installed: https://github.com/halkyonio/primaza-poc/pull/138
- [ ] Complete e2e logic using the Quarkus Super Hero application: https://github.com/halkyonio/primaza-poc/pull/145

**Comment by Sgitario** [comment]
@cmoulliard @aureamunoz , so when creating a new claim, the service request will be a combination of <service name>-<service version>-<credential name> ? 
When the last piece "-<credential name>", we perhaps should use the first credential found in the service?

**Comment by aureamunoz** [comment]
> When the last piece `-<credential name>`, we perhaps should use the first credential found in the service?

I don't think the credential should be in the request.

mmm, given that we have n Credentials per Service, yes, we need to choose one dependending on something, at the moment it can be ok to choose the one that we find first, yes.

**Comment by Sgitario** [comment]
And for the PoC purpose, the service-credential should be linked to the claim entity as well?

**Comment by cmoulliard** [comment]
> I don't think the credential should be in the request.

Correct

**Comment by cmoulliard** [comment]
claiming job : process able to change the status of the claims when a match occurs
service running job or rest endpoint : process able to check for a list of registered services, the k8s service/endpoint according to one of the clusters defined

As soon as a `claim` is created (= status new), then the `claiming job` will process it and will change the status from `new` to `pending`. 

All the `pending` claims will be then checked if there is a `service registered` matching the claim request (key = "service name" + "version"). 

if this is the case, then the job will call the `service running` job/endpoint in order to find a k8s service using the information of the service registered (= protocol + port. E.g tcp:3306). 

If this is the case, then the URL or K8s DNS name is populated to let a microservice to access the service (e.g: mysql-1.<namespace>.<k8s_service_FQName>:3306) - see: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/.

If the job is not able to find a k8s service (because not yet installed, not yet started, ...), then the job will increase the counter of the attempts (we should certainly add a new field to the claim supporting that). After x attempts, then the job will move the status from `pending` to `error`.

If a service has been discovered and the URL created (= then we must set the field URL of the claim), then the job can process to the next step. During this next step, the job will search about a credential matching the `service registered`. As several credentials could be created for one service, I suggest for the moment that we only take the first one of the list.
Extract the user/password from the credential and set the field credential of the claim.

If the fields URL + credentials are not empty, hen the jobwill create a k8s secret against the current or defined namespace and will change the status from `pending` to `bind`. If no credentials exist, then the status should move to `error` and comment appended to the `claim status comment` field (see hereafter comment).

Remark: That should be great to have a `claim status comment` field where the job will add information about what it happened.

**Comment by cmoulliard** [comment]
From the primaza service selected, the Claim URI should be populated following the 4 cases described hereafter:

1. app + service within same ns, cluster -> app can access the service using: `protocol://service_name:port`
2. app + service in different ns, same cluster -> app can access the service using: `protocol://service_name.namespace:port`
3. app + service running in another cluster -> app can access the service using ingress route, OpenShift route such as `protocol://project_or_service_name.namespace.IP.port`. **WARNING**: If the proxy cannot handle TCP to HTTP than it will be impossible to use an ingress or route. To be checked
4. app + service running on a standalone machine, VM or exposed by a cloud provider -> app can access the service using: `protocol://hostname_or_ip_or_FQName:port`

**Comment by Sgitario** [comment]
> From the primaza service selected, the Claim URI should be populated following the 4 cases described hereafter:
> 
> 1. app + service within same ns, cluster -> app can access the service using: `protocol://service_name:port`
> 2. app + service in different ns, same cluster -> app can access the service using: `protocol://service_name.namespace:port`
> 3. app + service running in another cluster -> app can access the service using ingress route, OpenShift route such as `protocol://project_or_service_name.namespace.IP.port`. **WARNING**: If the proxy cannot handle TCP to HTTP than it will be impossible to use an ingress or route. To be checked
> 4. app + service running on a standalone machine, VM or exposed by a cloud provider -> app can access the service using: `protocol://hostname_or_ip_or_FQName:port`

what do we know about `app`? I understand that this is the application that originates the claim, but at the moment, we don't have/store any information about it as part of the claim entity. Is this something we need to also add?

**Comment by cmoulliard** [comment]
> what do we know about `app`? I understand that this is the application that originates the claim, but at the moment, we don't have/store any information about it as part of the claim entity. Is this something we need to also add?

Correct. Here is what I'm thinking to do for the demo till we will integrate primaza with another systems able to populate a Claim CRD, etc.

- As soon as a Claim contains a URL and credentials, then primazaJob will create a Secret
- From the claim screen (edit mode) or claims table, we provide a new button (`bind`)
- When we will click on this button, we will display a list of the Deployment on the cluster
- The user selects a deployment and then we update it to mount the secret created for a claim
- If the deployment is the Quarkus Petclinic, then it should be able to consume the ENV vars to setup the datasource from the secret and then the App should be able to access the Service/DB

WDYT ? @Sgitario @aureamunoz

**Comment by Sgitario** [comment]
I think that having a workflow without human interaction is better even for a demo. 
As I understood, the workflow was as:
1.- Create my application on cluster "my-cluster". An application consists of an image, a deployment/service, and N claims. The deployment will wait until the secrets are installed (one secret per claim). 
2.- Once the claim is fulfilled: this means that there is a service that can be used by the application, this will generate a secret within the same namespace where the application deployment is installed. 
3.- Kubernetes will auto-start the deployment when all the secrets are present.

**Comment by cmoulliard** [comment]
> 1.- Create my application which consists of a container image, a deployment/service, and N claims.

We dont have yet a clear definition about what a claim could be. When we designed Halkyon 3 years ago we used the word `capability` in order to be able to not only refer to something that the application needs but also should have access, should be `bind`. According to this definition, a claim could be a Service/APi and tomorrow been extended to request a certificate, to secure a HTTP endpoint, ... 

To come back to your point, I think that at the beginning we will have a relation 1-1 between an application/microservice and a claim as the claim will let us to express `I want to access a NoSQL, SQL, Broker, etc service` and only one claim will be supported.

Long term, for sure, we should be able from an application to generate x claims as they could refer to a service, capability, etc

**Comment by cmoulliard** [comment]
> The deployment will wait until the secrets are installed (one secret per claim).

If the secret is mounted as a volume, then for sure, the deployment will wait. But, when you generate the deployment, the user does not yet that ultimately their deployment will be modified to mount a secret, then the process which is taking place will be a 2 steps process as first:

1. Deployment will take place (post mvn command executed)
2. A claim will be created(manually) as no dekorate or client tool is currently able to generate a Claim
3. Claiming + binding is taking place on primaza
4. End of the process (= url + credential exist and can be integrated in a secret), a secret is populated
5. User select using the list of the deployment using primaza UI the one where they want to mount/inject the secret
6. Secret and volume are included part of the deployment (= this is what SBO do)
7. A kubectl rollout is taking place to redeploy the pod and to let the app to access the service

remark: Ideally, steps 4-7 should be automated with the help of the SBO or another component deployed on k8s (halkyon ctrl, Application svc ctl, etc)

**Comment by Sgitario** [comment]
In the future, I think all the steps can be and should be automated, but let's continue using this approach for the PoC. 

Moreover, I think the step 4. can be skipped/or merged with step 5. because we cannot populate the secret until we know the deployment target. So, the scope of this issue involves the steps 5-7:
- Design a new page to see the deployments in all the clusters
- Generate the secret after selecting the claim and deployment. The secret must include the endpoint according to https://github.com/halkyonio/primaza-poc/issues/87#issuecomment-1318245939. 
- When the secret is installed, we need to rollout the deployment so that the application can start

Let me know if this is correct and I will update the issue description.

**Comment by cmoulliard** [comment]
> because we cannot populate the secret until we know the deployment target.

Why do you say that as the secret content is independent if it should be mounted in pod, replicaSet, daemonSet, Job, KtivnaeServing, etc ?

**Comment by Sgitario** [comment]
> > because we cannot populate the secret until we know the deployment target.
> 
> Why do you say that as the secret content is independent if it should be mounted in pod, replicaSet, daemonSet, Job, KtivnaeServing, etc ?

Because the endpoint depends on where the application is running (see rules: https://github.com/halkyonio/primaza-poc/issues/87#issuecomment-1318245939)
